security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        
    role_hierarchy:
     
        ROLE_APPRENANT: ROLE_USER
        ROLE_ORGANISME: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN 
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        
    firewalls:
               
        main: 
            pattern: ^/
            
            anonymous:    true
            access_denied_handler: redirect.after.denied
            form_login:
              
              login_path: /login
              check_path: /login_check
              success_handler: redirect.after.login
             
           
               
               
            logout:
                path:   /logout
                success_handler: redirect.after.logout
            
            
            
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/organisme/register, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin/, role: ROLE_ADMIN}
        - { path: ^/apprenant/, role:  ROLE_APPRENANT}
        - { path: ^/organisme/, role:  ROLE_ORGANISME} 
        - { path: ^/admin/afficherCompte, role:  ROLE_ADMIN}
        - { path: ^/admin/detailCompte , role:  ROLE_ADMIN} 